### ISSUE TITLE
How to use the `-browsers` variants?

### ISSUE THREAD

**Issue by m90** [CircleCI-Public/cimg-node#169]
I might be missing something very obvious here. I am trying to migrate a setup using "legacy" `circleci` Docker image to `cimg` ones. Some of them run on `circleci/node:14-browsers` which I migrated to `cimg/node:14.17-browsers`.

After having done so, my tests aren't able to run anymore as the `chrome` executable cannot be found anymore. SSHing into the build I found that no browser at all (Firefox, Chrome) is installed in the container. Looking at the Dockerfile here: https://github.com/CircleCI-Public/cimg-node/blob/63393c4d8cafdc66c628eeb9f25bd3b39ca8bb2d/14.17/browsers/Dockerfile I can also see that only browser dependencies, but no browsers are being installed.

Is this expected behavior? Am I supposed to install the browsers I require myself with the next gen images or am I doing something wrong? (I would be fine with installing the browsers myself, I would just find it very surprising if I had to do it in a `-browsers` variant, so I wanted to check if I'm doing something wrong here)

**Comment by felicianotech** [comment]
Hi. Please read the "Browsers" section of the [readme for this repo](https://github.com/CircleCI-Public/cimg-node#browsers). It explains the change. To summarize here, you need to use the browsers variant image along with the Browser Tools CircleCI orb in order to get the browsers to be available.

It is one extra step compared to the legacy images, but offers flexibility now as can use whatever version of Node.js you want yet lock to specific browser releases.
