### ISSUE TITLE
cimg/node:14.17.4 policykit vulnerability CVE-2021-4034

### ISSUE THREAD

**Issue by hamisor** [CircleCI-Public/cimg-node#208]
`cimg/node:14.17.4` which uses `cimg/base:2021.07` as the base has `policykit-1/now 0.105-26ubuntu1.1 amd64` installed which is subject to the vulnerability [CVE-2021-4034](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4034).

Ubuntu has pushed out new policykit-1 [patch](https://launchpad.net/ubuntu/+source/policykit-1/0.105-26ubuntu1.2) to mitigate this issue.

I can see the latest base image [`cimg/base:2022.02-20.04`](https://hub.docker.com/layers/cimg/base/2022.02-20.04/images/sha256-c14e6c92ef2dcf98debc6ecfdbb6963414d4db5b39044f738c52cf6c47c7ad0e?context=explore) has the updated policykit-1 0.105-26ubuntu1.2 installed.

I would like to request an update of the base image for `cimg/node:14.17.4` or any other node images use the `cimg/base:2021.07` image.

**Comment by JalexChen** [comment]
Hi @hamisor,

Thanks for letting us know - I can make these changes in a bit. However, if you were interested in making these changes on your end in the meantime, you could run `./shared/gen-dockerfiles.sh 14.17.4` in your shell and it will generate a new Dockerfile that uses our latest base image, which points to cimg/base:2022.01

**Comment by felicianotech** [comment]
I'd like to add, `sudo apt-get update` and `sudo apt-get -y upgrade` can be run in the image to update the policykit package to one with a fix. Or instead of "upgrade", an install of a specific package will just update that one, saving some time.

Most importantly though, this CVE doesn't really affect a CI build unless you are incorporating one of Ubuntu's packages into your own code. The privilege escalation is not a danger because we allow password sudo access in the first place in the image. The image already allows easier access to root then the CVE would.

**Comment by hamisor** [comment]
thanks for the clarification @felicianotech. We are only using this node image for the circle ci build not as the base of our application, so it is not a priority to update the base image at all. Just wondering how often this node image gets updated with the base image?
