### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by 100terres** [CircleCI-Public/cimg-node#216]
Hi :wave: I was wondering if it would be possible to include `pnpm` in this (or another) node image as package manager. It's already ship with `npm` and `yarn`, maybe it could also include `pnpm` :slightly_smiling_face: 

- https://pnpm.io/
- https://github.com/pnpm/pnpm

**Comment by stephenhmarsh** [comment]
I came here to also ask for pnpm to be added!  It's already [a supported package manager of Node's corepack ](https://nodejs.org/api/corepack.html#supported-package-managers)since 16.13.  

I'm currently blocked on using it in CI until I can figure out a way to make the `pnpm` executable available to my downstream jobs. It really should be part of the container!
