### ISSUE TITLE
Snyk Critical Vulnerabilities

### ISSUE THREAD

**Issue by Cristian-Vt** [CircleCI-Public/cimg-node#271]
Hello,

Based on Snyk report there are 5 Crytical vulnerabilities.
Is this something Circle Ci would be interested in fixing?
How does Circle Ci manage dependency management for the docker/orbs provided
<img width="722" alt="Screenshot 2022-08-04 at 13 07 32" src="https://user-images.githubusercontent.com/95423007/182843043-df2782bf-866a-42ab-9bdc-9b109f7727ca.png">
?

thank you

**Comment by felicianotech** [comment]
Hi,

Great question. Images are snapshots in time. So we typically don't go back to a released image to update it for any reason. We will for certain security fixes but this is rare because most security problems we come across don't have have an effect in the sandboxed Docker environment that we run.

In this particular case, which image was this run on? The screenshot leads me to believe it was `node:18.7.0-bullseye`. If so, that is not a supported CircleCI image.
