### ISSUE TITLE
Recent versions of image cause jest to fail

### ISSUE THREAD

**Issue by korya** [CircleCI-Public/cimg-node#279]
The recent versions of `cimg/node:lts-browsers` cause Jest to fail our unit test.

The problem is in rendering a localized date. The following test fails when invoked using `LANG=en_US TZ=Pacific/Tahiti jest`:

```js
test('render localized date', () => {
  const str = new Date('2017-10-29T14:55:30Z').toLocaleString(undefined, {
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    weekday: 'long',
    timeZoneName: 'short',
    timeZone: 'America/Toronto',
  });

  expect(str).toEqual('Sunday, October 29, 10 AM EDT');
});
```

It worked this way in CircleCI for years. It still works on my laptop (MacOs, Node v18.5.0).

But it stopped working in recent versions of `cimg/node:lts-browsers`, it fails with the following error message:

```
expect(received).toEqual(expected) // deep equality

Expected: "Sunday, October 29, 10 AM EDT"
Received: "Sunday, October 29 at 10 AM EDT"
```

That is it returns `Sunday, October 29 at 10 AM EDT` instead of `Sunday, October 29, 10 AM EDT`. (Side note: we noticed that the former is usually returned by Chrome).

Summary:
- A good version of the image is cimg/node@sha256:542f4764aa5e3dd7e9372ac3ede108639cf95bc752b5065ce0d3f8941a10834e. The tests works as expected.
- A recent bad version of the image is cimg/node@sha256:5f2070d5e582a32f977e14e8d7e611acf91e4affb10dc4cf9e536e040dfd7038. The tests fail with the error above.
- The failing build: https://app.circleci.com/pipelines/github/PlanitarInc/walk-inside-app/6596/workflows/f3e2a1b6-8c2b-45ea-85e2-521812b9111d/jobs/42877

**Comment by KyleTryon** [comment]
This issue likely stemming from the browser rather than the OS or image as we are dealing with a browser API. You may be able to resolve this by downgrading the browser version to a previously used browser. 

However, MDN docs tell us explicitly _not_ to compare toLocaleString to a static value, and that formatting changes are intended as a part of the spec.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#avoid_comparing_formatted_date_values_to_static_values

> Most of the time, the formatting returned by toLocaleString() is consistent. However, this might change in the future, and isn't guaranteed for all languages; output variations are by design, and allowed by the specification.
